sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: runner
    username: root
    password: 123456


  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t94YJ9BbTMqgyK8Pa6T
    access-key-secret: GXwASuwyKZ8BsvsIg5gXl6DkqFmBLO
    bucket-name: gandalfmaster

  wechat:
    appid: wx8ed143c01cedfa48
    secret: 9489fa88aa6c43345af2ad47f501866a